on: 
  push:
    branches:
      - master







jobs:
  build:
    runs-on: ubuntu-latest


    steps: 
      
      -name: 'Before1'
        run: ls

      -uses: actions/checkout@v3 

      -name: 'After'
        run: ls  




